version: "3"

services:
  chowdown:
    image: jekyll/jekyll
    restart: always
    container_name: chowdown
    command: jekyll serve --force_polling --livereload --livereload-port 35729
    ports:
      - "80:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
